### PR TITLE
Create Projects and Add a list of todos for the project

### PR DESCRIPTION
**Pull request by nganifaith**
This is a basic todo app. That allows the user to create a project and add a list of activities (todos) to it.
The program starts with a default project in which a user can add todo to it using the plus sign.
A todo just contains title, description and priority.

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, @nganifaith 👋🏾 👋🏾 congratulations on making it this far 😄 . 

#### Highlights

- You have used localStorage in your app ✔️
- You can create a project and assign it a todo ✔️ 
- You have hosted your app online ✔️  

#### To improve
However, the following can be improved ⬇️ 
- [x] You are missing the `@babel/core` module in your package.json. Kindly add it
- [x] In your README file, after a user has `cd` in the folder they need to run `npm i` to install packages in node_modules. Kindly add that.
- [x] Add .vscode in your .gitignore file
- [x] From the live link in your README file, there should be a default project. Currently, there is none
* [x] Necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack serve --mode development --open" // optional
  },
```

- [x]  I have reviewed this project with the live project shared by the student. I had issues with starting the webpack server as shown in the image below ⬇️ 
image


That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Changes Required❌

# 👋  @nganifaith 

#### You have done a good job on this one so far, you addressed most of the issues raised in the previous but there are few others that we have to address again.
> I like the UI, good job!🤗

* [x] Unrelated code should not be committed, you can add their path to `.gitignore`, as mentioned in previous review. In this case, after adding the path of `.vscode` to the gitignore, use the a  `git rm `command to delete it from the remote branch, **or** you can manually delete it(.vscode) before your next push after which you add the path to `.gitignore` so they don't get committed again.

* [x] There should be a default project name, you can call it `default` at home screen we should able to see this project and when we select it we should see todos that were store under this title alone. After creating a new project name we should be able to see the newly created project by it name ie `default` `new project`, When I click default I should only project stored under default project name, when I click `new project` I should not see any project store under default but on under `new project`  

#### That is it, kindly make the changes and submit a new re-review😇

#### Happy coding😎

Addo Forison

**Comment by nganifaith** [comment]
Hello, @Forison Thanks for your review. However,  your second point is not clear. 
Is the issue the name of the default project or you don't see a default at all.?  And I don't think adding ToDo to the default project is part of the requirements. The current default project is called code review

**Comment by Forison** [comment]
> Hello, @Forison Thanks for your review. However, your second point is not clear.
> Is the issue the name of the default project or you don't see a default at all.? And I don't think adding ToDo to the default project is part of the requirements. The current default project is called code review

I sought to suggest that you treat each project like  tab/link which when click you see the todos associated with it only. ie I click code review, I can add or view todos in it, and while I am there(code-review) I can navigate to go to another project I have created and view its todos.

**Comment by nganifaith** [comment]
> > Hello, @Forison Thanks for your review. However, your second point is not clear.
> > Is the issue the name of the default project or you don't see a default at all.? And I don't think adding ToDo to the default project is part of the requirements. The current default project is called code review
> 
> I sought to suggest that you treat each project like tab/link which when click you see the todos associated with it only. ie I click code review, I can add or view todos in it, and while I am there I should able to go to another project I have created.

Did you test my project or you are making an assumption. that is exactly how it functions. You can read from the previous review. And with this, you are blocking my project from being approved.

**Comment by Forison** [comment]
> > > Hello, @Forison Thanks for your review. However, your second point is not clear.
> > > Is the issue the name of the default project or you don't see a default at all.? And I don't think adding ToDo to the default project is part of the requirements. The current default project is called code review
> > 
> > 
> > I sought to suggest that you treat each project like tab/link which when click you see the todos associated with it only. ie I click code review, I can add or view todos in it, and while I am there I should able to go to another project I have created.
> 
> Did you test my project or you are making an assumption. that is exactly how it functions. You can read from the previous review. And with this, you are blocking my project from being approved.

I was still seeing todos from code-review after I created my own todo, that is why I made that suggestion.

**Comment by Forison** [comment]
> > > > Hello, @Forison Thanks for your review. However, your second point is not clear.
> > > > Is the issue the name of the default project or you don't see a default at all.? And I don't think adding ToDo to the default project is part of the requirements. The current default project is called code review
> > > 
> > > 
> > > I sought to suggest that you treat each project like tab/link which when click you see the todos associated with it only. ie I click code review, I can add or view todos in it, and while I am there I should able to go to another project I have created.
> > 
> > 
> > Did you test my project or you are making an assumption. that is exactly how it functions. You can read from the previous review. And with this, you are blocking my project from being approved.
> 
> I was still seeing todos from code-review after I created my own todo, that is why I made that suggestion.

You are right I may have mess up the project earlier, here is the basis of the first recommendation 

* [x] Files not related to the project should not be committed   ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**Review by whiz25 — APPROVED** [review]
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested changes. Merge and proceed to the next project.


### Martin Afani
#### Slack: whiz25

**Pull request merged**
